N=length(u);
data.Ts = 1;
data.u(:,1) = u(1:N,2);
data.y(:,1) = h(1:N,2);

t = u(1:N,1);

% Plot
a_width=1;
s_width=1;
f_size=9;
f_wt = 'normal';
grd='off';

hdl=figure(1);
set(hdl,'Color', [1 1 1],'Position', [104 50 313 455]);
subplot(2,1,1);
hdl=plot(t,data.u(:,1),'b-');
set(hdl,'LineWidth',s_width);
hdl=gca;
set(hdl,'XLim',[0 1000],...
      'YLim',[0 12],... 
      'XTick',[0 200 400 600 800 1000],...
      'XTickLabel',[],...
      'YTick',[0 6 12],...
      'XGrid',grd,...
      'YGrid',grd,...
      'LineWidth',a_width,...
      'FontSize', f_size,...
      'FontWeight',f_wt);
Title('Single tank input - output data');
Ylabel('u');  

subplot(2,1,2);
hdl=plot(t,data.y(:,1),'b-');
set(hdl,'LineWidth',s_width);
hdl=gca;
set(hdl,'XLim',[0 1000],...
      'YLim',[0 50],... 
      'XTick',[0 200 400 600 800 1000],...
      'XTickLabel',[],...
      'YTick',[0 25 50],...
      'XGrid',grd,...
      'YGrid',grd,...
      'LineWidth',a_width,...
      'FontSize', f_size,...
      'FontWeight',f_wt);
Ylabel('y1');  
Xlabel('Time');


